version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-app
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - TZ=America/New_York
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/app
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: trading-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  redis_data:
    driver: local
